In [115]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, Normalizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [116]:
df_data = pd.read_csv('titanic_train.csv')
df_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [117]:
df_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [118]:
df_data = df_data.drop('Cabin', axis = 1)
df_data = df_data.drop('Name', axis = 1)
df_data = df_data.fillna(df_data['Age'].mean())
df_data = df_data.fillna(0)
df_data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [119]:
df_data = pd.get_dummies(df_data)
df_data.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Ticket_110152,...,Ticket_W./C. 6607,Ticket_W./C. 6608,Ticket_W./C. 6609,Ticket_W.E.P. 5734,Ticket_W/C 14208,Ticket_WE/P 5735,Embarked_29.69911764705882,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,7.2500,0,1,0,...,0,0,0,0,0,0,0,0,0,1
1,2,1,1,38.0,1,0,71.2833,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,1,3,26.0,0,0,7.9250,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4,1,1,35.0,1,0,53.1000,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,5,0,3,35.0,0,0,8.0500,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [120]:
y_data = df_data.pop('Survived')
x_data = df_data

In [121]:
logreg = LogisticRegression(fit_intercept=True)
logreg.fit(x_data, y_data)

logreg.predict(x_data) == y_data

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14     False
15      True
16      True
17     False
18      True
19      True
20      True
21     False
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...
861     True
862     True
863     True
864     True
865     True
866     True
867     True
868     True
869    False
870     True
871     True
872     True
873     True
874     True
875     True
876     True
877     True
878     True
879     True
880     True
881     True
882    False
883     True
884     True
885     True
886     True
887     True
888     True
889     True
890     True
Name: Survived, Length: 891, dtype: bool

### Accuray , Error

In [122]:
accuracy = sum(logreg.predict(x_data) == y_data) / len(y_data)
accuracy

0.87654320987654322

In [123]:
error = 1 - accuracy
error

0.12345679012345678

In [124]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, accuracy_score

### Naive_Bayes

In [125]:
clf_M = MultinomialNB()
clf_M.fit(x_data, y_data)

clf_B = BernoulliNB()
clf_B.fit(x_data, y_data)

scores_M = cross_val_score(clf_M, x_data, y_data, cv=5)
print("Multinomial Accuracy: %0.2f (+/- %0.2f)" % (scores_M.mean(), scores_M.std() * 2))

scores_B = cross_val_score(clf_B, x_data, y_data, cv=5)
print("Bernoulli Accuracy: %0.2f (+/- %0.2f)" % (scores_B.mean(), scores_B.std() * 2))

Multinomial Accuracy: 0.66 (+/- 0.11)
Bernoulli Accuracy: 0.79 (+/- 0.04)

### Pipe_lr

In [135]:
pipe_lr = Pipeline(steps=[('scl', StandardScaler()), ('clf', LogisticRegression())])
pipe_lr.fit(X = x_data, y = y_data)
pipe_rf = Pipeline(steps=[('scl', StandardScaler()), ('clf', RandomForestClassifier(n_estimators=1000,n_jobs=1, criterion='entropy'))])
pipe_rf.fit(X = x_data, y = y_data)

Pipeline(steps=[('scl', StandardScaler(copy=True, with_mean=True, with_std=True)), ('clf', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=1000, n_jobs=1, oob_score=False,
            random_state=None, verbose=0, warm_start=False))])

In [136]:
from sklearn.metrics import classification_report
print(classification_report(y_data, pipe_lr.predict(x_data)))

             precision    recall  f1-score   support

          0       0.99      0.99      0.99       549
          1       0.99      0.99      0.99       342

avg / total       0.99      0.99      0.99       891

In [137]:
from sklearn.metrics import classification_report
print(classification_report(y_data, pipe_rf.predict(x_data)))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       549
          1       1.00      1.00      1.00       342

avg / total       1.00      1.00      1.00       891

In [140]:
pipe_lr.predict_proba(x_data)[:,1]

array([  3.44096612e-03,   9.98581195e-01,   9.97390762e-01,
         9.59884874e-01,   2.85773075e-03,   3.44547743e-03,
         3.44770546e-03,   5.15272389e-05,   9.99678200e-01,
         9.82675300e-01,   9.99238693e-01,   9.96817925e-01,
         4.06168005e-03,   2.10454886e-06,   1.04491069e-02,
         9.96061042e-01,   1.04812996e-03,   9.92628391e-01,
         8.37250869e-03,   9.97627049e-01,   1.41762155e-03,
         9.92228797e-01,   9.98307906e-01,   9.93999103e-01,
         1.24687687e-02,   9.69292109e-01,   3.82868134e-03,
         8.36244237e-02,   9.97274758e-01,   3.27059004e-03,
         5.05015913e-03,   9.99677600e-01,   9.97274016e-01,
         1.51686893e-03,   5.30702077e-02,   3.48081925e-02,
         9.92159690e-01,   3.97869958e-03,   1.67086656e-02,
         9.99966085e-01,   7.47133034e-03,   1.82922478e-02,
         3.83313266e-03,   9.94034323e-01,   9.98043440e-01,
         3.27165609e-03,   3.05287947e-03,   9.97274114e-01,
         3.03539027e-03,   1.77720662e-02,   8.36654590e-04,
         3.97717026e-03,   9.99954152e-01,   9.97716093e-01,
         2.86602009e-03,   9.93847084e-01,   9.98532312e-01,
         3.92793019e-03,   9.97150830e-01,   1.10193517e-04,
         4.47349963e-03,   9.99804528e-01,   3.06227091e-02,
         6.04569239e-05,   5.96216854e-03,   9.91292624e-01,
         9.98016810e-01,   4.14628850e-03,   9.95679399e-01,
         2.70689992e-03,   4.03903653e-03,   2.88376834e-02,
         8.04297922e-03,   3.72661985e-03,   6.61951108e-01,
         3.64740745e-03,   3.27089577e-03,   3.27186429e-03,
         9.90644376e-01,   9.95599970e-01,   3.90235498e-03,
         9.91585999e-01,   9.97274565e-01,   5.62656993e-03,
         9.98765105e-01,   9.20418368e-01,   3.32518149e-05,
         3.27192936e-03,   9.64350915e-01,   3.73173815e-03,
         3.32757273e-03,   4.06096578e-03,   3.70906608e-03,
         2.30337220e-01,   1.23479349e-03,   3.27198143e-03,
         2.56664054e-03,   9.94882610e-01,   9.96412945e-01,
         3.00705411e-02,   9.10391608e-03,   3.27105845e-03,
         1.04844972e-02,   3.01637457e-03,   1.91440629e-03,
         3.40666043e-03,   9.97753905e-01,   9.91507391e-01,
         2.63039124e-03,   9.26467189e-01,   1.63386222e-03,
         1.62740778e-02,   3.89641577e-03,   9.35591719e-03,
         2.02841635e-02,   3.97843718e-03,   7.71962077e-04,
         3.55839361e-05,   1.46054083e-01,   2.04324301e-02,
         2.83467882e-03,   3.27215065e-03,   2.20904926e-02,
         9.97787652e-01,   4.60338448e-04,   9.88003316e-01,
         3.44180885e-03,   9.92038815e-01,   9.96849675e-01,
         2.11897447e-03,   3.56410152e-03,   4.05599295e-03,
         6.86663406e-03,   9.97716602e-01,   4.64744398e-03,
         5.44112076e-03,   9.98899226e-01,   4.37226384e-02,
         5.02730299e-03,   1.11744724e-02,   2.80996255e-03,
         9.97683285e-01,   9.61878843e-01,   4.31729345e-03,
         5.24304100e-03,   3.70836936e-01,   9.91762460e-01,
         2.40511683e-02,   2.41328959e-01,   3.24225832e-03,
         2.54935111e-03,   9.69522947e-01,   1.44143794e-03,
         1.89712216e-03,   3.26776478e-03,   3.98354922e-03,
         9.98242653e-01,   3.24851725e-03,   3.27621364e-03,
         2.08174629e-05,   1.95086624e-03,   9.97253504e-01,
         3.56752741e-03,   4.31833372e-03,   1.48025558e-03,
         7.67848236e-01,   9.98437346e-01,   6.89132682e-04,
         5.33002554e-03,   7.41345652e-01,   2.78834866e-03,
         8.68077252e-04,   9.99969093e-01,   3.97884764e-03,
         3.71590520e-03,   3.43282195e-03,   2.11937842e-05,
         1.00185919e-02,   4.22359848e-03,   1.47727615e-01,
         8.94107596e-03,   4.85652206e-03,   4.38047450e-01,
         9.89434527e-01,   9.98410145e-01,   5.49731941e-03,
         9.54154412e-01,   9.92385270e-01,   1.60912191e-05,
         2.78168477e-03,   9.97823382e-01,   5.16644640e-03,
         9.97501070e-01,   8.70960430e-01,   9.98340776e-01,
         9.97201110e-01,   3.44227252e-03,   2.04615605e-03,
         9.97275099e-01,   1.06337703e-02,   3.41739451e-03,
         2.08253406e-05,   2.92644404e-03,   2.58726810e-03,
         9.92605050e-01,   2.01774571e-02,   7.73659583e-02,
         3.27374178e-01,   9.98243065e-01,   9.93518838e-01,
         3.72613694e-03,   9.97654585e-01,   3.89192568e-03,
         4.22386014e-03,   3.00653191e-03,   9.91996833e-01,
         9.97317360e-01,   3.14874308e-02,   9.99202185e-01,
         4.20740597e-03,   9.92790089e-01,   4.47753312e-03,
         1.72209749e-03,   3.27185280e-03,   9.87337998e-01,
         3.90564084e-03,   9.93592286e-01,   4.01636744e-03,
         5.25412683e-03,   9.10383804e-03,   9.72569479e-01,
         3.32677212e-03,   1.98657310e-03,   9.97980486e-01,
         4.71712706e-03,   8.94155733e-03,   2.74002541e-03,
         9.95556831e-01,   5.14971423e-03,   3.96871040e-03,
         3.89183921e-03,   9.96897756e-01,   4.29173229e-03,
         3.89133154e-03,   3.80545696e-03,   2.32106551e-02,
         9.39094284e-03,   9.99815891e-01,   9.86277782e-01,
         1.37170279e-05,   3.26799997e-03,   9.36472354e-04,
         2.67224421e-03,   2.59846884e-05,   1.28452960e-02,
         9.97105372e-01,   9.99308352e-01,   9.98940335e-01,
         9.99992735e-01,   9.93991482e-01,   3.44269665e-03,
         5.79762280e-01,   2.74857414e-02,   4.26760342e-03,
         9.14033409e-03,   3.71023745e-03,   3.56585250e-04,
         9.91431063e-01,   8.98085761e-01,   9.16197227e-01,
         3.69886112e-02,   3.30398250e-01,   9.95118096e-01,
         4.96372951e-03,   9.97275595e-01,   9.93220062e-01,
         7.51098377e-03,   4.15574237e-03,   6.53518793e-04,
         8.93645372e-01,   1.03268645e-03,   3.40755746e-03,
         4.40929338e-03,   9.92513336e-01,   5.33162070e-03,
         3.57004070e-03,   9.91494180e-01,   3.89663870e-03,
         9.91480006e-01,   9.97837358e-01,   9.80061851e-01,
         9.99987933e-01,   4.30426736e-03,   9.49536572e-03,
         3.73214689e-03,   5.96455994e-03,   4.34815937e-03,
         8.53001819e-01,   9.93814181e-01,   8.62518452e-01,
         9.97275764e-01,   9.83003482e-01,   4.66069973e-01,
         9.98126738e-01,   3.27334282e-03,   1.46242047e-02,
         9.99289689e-01,   9.60816918e-01,   4.35967545e-02,
         9.99996834e-01,   9.99875981e-01,   9.99565497e-01,
         9.61215317e-03,   3.40803044e-03,   4.95179327e-02,
         9.97392386e-01,   9.72076376e-01,   2.34003405e-03,
         9.99330354e-01,   9.98218533e-01,   3.89268023e-03,
         3.48850292e-03,   9.98106724e-01,   9.99815043e-01,
         2.08484284e-05,   9.50910089e-01,   1.12254117e-03,
         9.97536638e-01,   9.93627749e-01,   9.99821494e-01,
         9.99960106e-01,   3.99510446e-03,   1.19824533e-01,
         4.75513865e-05,   9.99996920e-01,   3.27258277e-03,
         3.64353868e-02,   9.99218258e-01,   9.90050603e-01,
         4.08269004e-03,   8.81407943e-01,   9.61021312e-01,
         4.39361137e-03,   4.64913345e-03,   3.72685241e-03,
         9.98360569e-01,   9.97238271e-01,   9.96733168e-01,
         9.94814224e-01,   2.34255444e-03,   3.82320185e-03,
         5.39461587e-03,   4.24891881e-03,   2.15297643e-05,
         3.83099096e-03,   3.41841724e-03,   9.99248854e-01,
         9.29281691e-03,   9.97276910e-01,   9.97276916e-01,
         2.56412098e-06,   4.52967111e-03,   1.40849785e-03,
         2.85399604e-03,   4.59027648e-02,   3.24488811e-03,
         9.97074312e-01,   9.97629268e-01,   9.97276207e-01,
         9.99488036e-01,   9.94537374e-01,   3.76359380e-03,
         4.14779717e-03,   1.44701070e-01,   1.99635557e-02,
         9.53972110e-01,   9.97681979e-01,   6.77089300e-03,
         4.62501940e-03,   4.14604141e-03,   9.46681045e-01,
         9.99995200e-01,   3.09168915e-03,   9.68239518e-01,
         3.27290235e-03,   1.06976861e-02,   2.85802705e-04,
         9.97537019e-01,   3.44341420e-03,   9.99129728e-01,
         9.77732156e-01,   9.92326950e-01,   2.55478494e-03,
         9.96248051e-01,   9.95555301e-01,   3.89674532e-03,
         8.82257871e-03,   3.75667265e-03,   4.80446219e-03,
         9.98098015e-01,   9.90627348e-01,   3.57087912e-03,
         9.26381674e-03,   3.83816777e-02,   9.87947055e-03,
         3.49276948e-03,   1.72169777e-03,   9.91479362e-01,
         3.97953456e-03,   9.11847749e-03,   3.27307198e-03,
         3.43807127e-03,   9.80214617e-01,   4.16081574e-03,
         9.90147027e-01,   8.94757178e-03,   9.97074422e-01,
         9.98209876e-01,   4.22539346e-03,   2.41808978e-02,
         3.83579669e-03,   4.15786320e-03,   3.32864916e-03,
         1.50776774e-02,   2.35153522e-04,   3.26914064e-03,
         9.97789593e-01,   9.83295948e-01,   3.44381090e-03,
         9.91295795e-01,   9.93940079e-01,   9.53929166e-01,
         9.96734628e-01,   4.31018034e-03,   2.86063813e-02,
         9.99993505e-01,   7.83743512e-03,   9.99457049e-01,
         1.64445385e-03,   4.12520563e-03,   9.49205260e-01,
         4.07425048e-03,   3.20792280e-03,   9.98100144e-01,
         9.91514192e-01,   9.95687628e-01,   9.99657780e-01,
         9.93399075e-01,   9.98832475e-01,   9.91762252e-01,
         4.08596480e-02,   2.91598503e-03,   5.93937693e-03,
         9.86594647e-01,   3.27432139e-03,   9.92235197e-01,
         2.45174803e-03,   9.98570925e-01,   9.96438021e-01,
         3.44401665e-03,   9.92108767e-01,   2.93753522e-03,
         3.93676221e-03,   2.77894836e-03,   3.27438668e-03,
         2.62768400e-03,   4.16279453e-03,   3.13399966e-03,
         3.44391860e-03,   9.99220256e-01,   3.26943423e-03,
         2.63721966e-03,   9.60863699e-01,   9.98835502e-01,
         9.69689819e-03,   8.42748526e-03,   6.30026412e-02,
         2.89171111e-03,   3.89554182e-03,   9.98733639e-01,
         1.33762493e-04,   4.16539466e-03,   1.78871330e-03,
         9.94344505e-01,   9.90853748e-01,   9.12466559e-03,
         9.99977797e-01,   3.54890584e-03,   3.25067194e-03,
         9.90876448e-01,   2.91623434e-03,   3.97670176e-03,
         3.23736946e-03,   2.65609842e-03,   3.98193630e-03,
         1.43439339e-05,   9.97393119e-01,   3.31866872e-03,
         3.95195926e-01,   3.73290554e-03,   4.32086444e-03,
         9.97529292e-03,   9.14235974e-03,   8.27174529e-03,
         9.99720262e-01,   4.90278079e-02,   9.95686885e-01,
         9.93788357e-01,   3.50177440e-03,   7.76623325e-01,
         9.91775250e-01,   3.27469358e-03,   9.93215956e-01,
         9.97436474e-01,   3.73107923e-03,   3.90798613e-03,
         9.97668889e-01,   4.69851964e-02,   9.97201736e-01,
         3.09239405e-03,   9.99760642e-01,   3.89827604e-03,
         3.83217543e-03,   9.97456420e-01,   3.83221672e-03,
         2.60639505e-03,   9.96438478e-01,   6.72499790e-03,
         2.55879408e-03,   3.54007247e-03,   9.99741122e-01,
         3.83226609e-03,   4.08267161e-03,   9.97239962e-01,
         8.92513313e-03,   9.98731698e-01,   4.02545867e-03,
         9.88318794e-01,   3.31518194e-03,   9.99183141e-01,
         9.90950926e-01,   1.06510172e-02,   8.82378493e-03,
         9.85397931e-01,   1.69872299e-02,   2.52242888e-03,
         9.99990057e-01,   9.93284066e-01,   2.29690912e-01,
         6.27225930e-01,   8.31481215e-01,   4.56715917e-03,
         3.44513410e-03,   9.92880628e-01,   9.97686103e-01,
         2.67424221e-03,   9.97760936e-01,   1.16687400e-01,
         9.76869953e-01,   9.96234778e-01,   3.44468731e-03,
         2.48505055e-03,   4.39863697e-03,   3.27503328e-03,
         8.94943203e-03,   3.33804398e-03,   4.14819758e-03,
         2.53330472e-03,   3.83252711e-03,   9.91296096e-01,
         9.89538416e-01,   9.96496878e-01,   9.93217361e-01,
         9.97277539e-01,   4.40188268e-03,   5.65040880e-03,
         9.97683465e-01,   9.73218557e-01,   9.13255834e-03,
         9.91296756e-01,   9.97729935e-01,   9.95714321e-01,
         1.76290793e-03,   5.49266086e-03,   3.84224107e-03,
         9.97179691e-01,   2.86795574e-03,   9.91109851e-01,
         3.89974601e-03,   3.27520319e-03,   2.85590150e-03,
         9.97845210e-01,   1.98559120e-03,   8.35472574e-03,
         3.28537748e-03,   4.25553369e-06,   9.63721608e-01,
         4.81469878e-02,   3.83271160e-03,   9.86133611e-01,
         9.68921269e-01,   3.27431926e-03,   5.44839534e-03,
         2.19806698e-03,   9.93940905e-01,   2.41810059e-03,
         3.25048093e-03,   9.94059221e-01,   9.64949345e-01,
         9.86413517e-01,   9.15944037e-04,   3.26910714e-03,
         9.96908074e-01,   3.44503943e-03,   2.86163065e-03,
         9.99316987e-01,   2.00116644e-05,   1.62514164e-02,
         9.99967354e-01,   4.54909701e-03,   2.77716831e-02,
         9.92346693e-01,   9.85841378e-01,   3.98157510e-03,
         5.06306808e-03,   2.78431151e-03,   2.27218855e-03,
         9.99925576e-01,   3.57142031e-03,   3.44504034e-03,
         9.89049218e-01,   1.71953536e-03,   9.94236014e-01,
         5.15543625e-03,   1.61090860e-02,   9.98101327e-01,
         3.09333008e-03,   4.87750521e-02,   2.35785435e-02,
         4.56900833e-02,   4.06490777e-03,   9.99489288e-01,
         3.08628173e-02,   7.10081185e-01,   9.99221484e-01,
         9.82348212e-01,   4.14878087e-03,   9.92083357e-01,
         3.27246853e-03,   9.97613304e-01,   3.27463957e-03,
         9.99217537e-01,   3.98555604e-03,   9.97278529e-01,
         1.02588193e-02,   2.14331401e-03,   3.27467880e-03,
         1.47540946e-02,   4.82356983e-03,   1.66335075e-02,
         9.84763506e-01,   3.00804305e-03,   3.85426713e-03,
         2.78232104e-03,   9.91907726e-01,   1.00335588e-03,
         4.65174696e-03,   3.27399683e-03,   2.26942067e-03,
         9.99993808e-01,   9.80351037e-01,   4.91814122e-03,
         1.28443113e-03,   9.92515844e-01,   4.16682268e-03,
         4.23208855e-03,   3.69484227e-03,   9.97979109e-01,
         3.82974765e-03,   9.94905813e-01,   9.14839044e-03,
         9.98556615e-01,   4.07418520e-03,   8.33291311e-05,
         1.69238103e-02,   4.56292444e-02,   4.32827538e-04,
         4.16403866e-03,   4.23232200e-03,   9.99849328e-01,
         9.88122257e-01,   9.99005053e-01,   7.10172049e-01,
         4.22464168e-03,   2.82626360e-03,   2.48492222e-03,
         2.19866020e-03,   9.97278244e-01,   1.71867629e-01,
         2.33903113e-03,   9.90396592e-01,   9.93309163e-01,
         1.80753292e-02,   3.82787401e-03,   3.13130723e-03,
         1.99531346e-02,   9.96857371e-01,   9.92667670e-01,
         7.64274548e-01,   9.91342557e-01,   9.99435794e-01,
         5.33939536e-03,   9.84963497e-01,   3.34064035e-03,
         1.05662443e-03,   4.14766854e-03,   9.63024190e-01,
         9.98155369e-01,   3.49474162e-03,   3.01496228e-03,
         9.94162180e-01,   3.85185544e-03,   3.89404251e-03,
         2.63014690e-03,   9.88811121e-01,   4.07081131e-03,
         9.37363085e-01,   9.97278463e-01,   4.27026282e-03,
         8.87254530e-03,   9.99616382e-01,   6.70417808e-01,
         4.16725204e-03,   4.82419746e-03,   4.82420583e-03,
         2.49137283e-03,   6.92118265e-04,   9.96875545e-01,
         3.27521516e-03,   3.27522170e-03,   9.93815297e-01,
         2.54091032e-02,   9.99424484e-01,   3.34128384e-03,
         9.91393578e-01,   8.71857325e-03,   1.05921466e-01,
         9.97966107e-01,   5.98531255e-03,   3.34179728e-03,
         9.98995396e-01,   9.88238691e-01,   3.02572474e-03,
         3.81740336e-03,   9.93365799e-01,   9.90253117e-01,
         3.41032546e-03,   5.24859863e-03,   2.93944447e-03,
         9.98597614e-01,   2.05499535e-03,   2.40880444e-03,
         9.93066823e-01,   9.99947615e-01,   4.40150437e-03,
         9.97831937e-01,   6.05382644e-03,   9.07052006e-03,
         2.84206547e-02,   3.09688351e-03,   3.74572574e-03,
         1.92227364e-03,   1.24166879e-02,   3.83394698e-03,
         9.94660905e-01,   4.23266372e-03,   3.44612321e-03,
         9.99591968e-01,   3.44605760e-03,   9.97850232e-01,
         9.98721617e-01,   9.99992672e-01,   5.42558543e-03,
         3.30401438e-05,   3.64836542e-03,   3.64965209e-03,
         9.97967092e-01,   5.97039809e-04,   7.64153345e-01,
         1.40308732e-03,   3.44621636e-03,   8.62136685e-03,
         8.99006182e-03,   5.99083156e-03,   3.65384659e-03,
         3.48622106e-03,   9.97507344e-01,   9.97020611e-01,
         3.80937907e-03,   3.25636531e-03,   5.82174946e-03,
         9.56989004e-01,   9.97895430e-01,   9.94463997e-01,
         9.91764619e-01,   3.17201047e-03,   4.35625333e-03,
         1.00703502e-02,   3.48630899e-03,   9.99953850e-01,
         3.57259025e-03,   2.29732319e-03,   3.79603885e-03,
         1.41491105e-02,   3.21322373e-03,   5.15706946e-03,
         9.59054425e-03,   1.83488954e-01,   2.26137974e-03,
         3.44184062e-05,   9.95178474e-01,   9.91777438e-01,
         4.44123030e-03,   9.99798099e-01,   1.35426275e-03,
         3.44139931e-03,   7.10420450e-01,   8.15640882e-01,
         9.91713369e-01,   9.98104000e-01,   9.74865560e-01,
         9.93082369e-01,   3.83439092e-03,   3.81768892e-03,
         4.23673086e-03,   9.98323836e-01,   3.98835792e-03,
         3.27682573e-03,   6.63489500e-01,   9.94435920e-01,
         4.06681019e-03,   1.42695458e-03,   9.69380515e-01,
         3.43871375e-03,   4.32345187e-03,   2.33939746e-03,
         2.09466960e-05,   3.40782665e-03,   4.63825142e-02,
         9.99995008e-01,   4.00696359e-05,   5.52805461e-04,
         1.75096850e-02,   9.99287410e-01,   1.52212445e-02,
         9.97684858e-01,   9.97138442e-01,   9.91832079e-01,
         9.94556339e-01,   3.83458167e-03,   1.68819455e-03,
         4.51364027e-03,   9.97581182e-01,   8.99576201e-03,
         4.73918045e-03,   9.97088703e-01,   9.98268635e-01,
         5.39239295e-03,   3.28608309e-03,   9.82609637e-01,
         3.57304658e-03,   9.99917418e-01,   4.90458028e-03,
         1.99679856e-03,   9.60011407e-01,   9.98606332e-01,
         3.48227607e-03,   4.15046643e-03,   3.27613176e-03,
         9.96180736e-01,   9.99441601e-01,   3.01674690e-03,
         9.70701378e-03,   4.38114092e-03,   3.64904355e-03,
         2.23014299e-02,   4.48274441e-03,   9.99305031e-01,
         1.41273018e-02,   9.94763147e-01,   3.26320355e-03])

In [144]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

scores = pipe_lr.predict_proba(x_data)[:, 1]
y_real = y_data
fpr_lr, tpr_lr, thresholds = roc_curve(y_real, scores)

roc_auc_lr = roc_auc_score(y_real, scores)
roc_auc_lr

0.99937153143940605

In [142]:
import matplotlib.pyplot as plt

plt.figure()
lw = 2
plt.plot(fpr_lr, tpr_lr, color='darkorange', lw=lw, label='ROC curve (area = %0.2f)' % roc_auc_lr)

plt.plot(fpr_lr, tpr_rf, color='blue', lw=lw, label='ROC curve of class {0} (area = {1:0.2f})'
        ''.format('rf', roc_auc_rf))

plt.plot([0, 1], [])